<a href="https://colab.research.google.com/github/Viktory4121/MORD/blob/main/%D0%94%D0%9E%D0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Динамические окрестностные модели (ДОМ)
####Вариант 5

In [74]:
import numpy as np
import pandas as pd
import random
import copy
import math
from prettytable import PrettyTable
import itertools as it

In [ ]:
#A={a1, a2, a3}

#какие дуги входят в позицию:
#Ox[a1]={a1}
#Ox[a2]={}
#Ox[a3]={a1, a2}

#в какие позиции входят v
#Ov[a1]={a1}
#Ov[a2]={a2}
#Ov[a3]={a3}

In [75]:
#количества состояний/входов/выходов
count = [3, 3, 3]
Sx = np.array([[1, 0, 1], [0, 0, 1], [0, 0, 0]])
Sv = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

print("Матрица смежности:")
print("Sx = ")
print(Sx)
print("Sv = ")
print(Sv)

Матрица смежности:
Sx = 
[[1 0 1]
 [0 0 1]
 [0 0 0]]
Sv = 
[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [102]:
def x1(x, v):
  return math.sin(x[0]**2 + math.log(abs(v[1] + v[0])) / x[2])

def x2(x, v):
  return math.cos(v[0] * x[2] - (x[1] / x[2])**3)

def x3(x, v):
  return math.sin(math.tan(x[2] * v[2]) - 3**(v[0]))

def v1(x, v):
  return (x[1] * v[0] * v[1] + math.tan(x[2])**2)

def v2(x, v):
  return (0.2 * v[0] + 33.0 * v[1] + v[2])

def v3(x, v):
  return (math.exp(x[0]) + .45 * math.log2(abs(x[1] * x[2])))

def y1(x, v):
  return x[0] * v[0] * math.sqrt(abs(x[0] / x[1]))

def y2(x, v):
  return math.sqrt(abs(math.sin(v[2])))

def y3(x, v):
  return v[2] * v[0] / v[0]

functions = [x1, x2, x3, v1, v2, v3, y1, y2, y3]

In [106]:
#Метод псевдообращения Бена-Израиля
def BenIsrael(A, eps):
  I = np.diag(np.diag(np.ones([len(A),len(A)])))
  buf = 1
  i = 1

  if(np.linalg.norm(A, ord='fro') != 0): #если не нулевая норма
    gamma = 1.6 / (np.linalg.norm(A, ord='fro')**2)
    A1 = gamma * (A.T)
    i += 1
    A2 = A1.dot(2*I - A.dot(A1))
    E = np.linalg.norm(A2 - A1, ord=np.inf) / np.linalg.norm(A1, ord=np.inf)
  else: #если нулевая норма
    A1 = np.zeros((len(A[0]), len(A)))
    buf = 0

  while(E >= eps and buf):
    A1 = A2.copy()
    A2 = A1.dot(2*I - A.dot(A1))
    E = np.linalg.norm(A2 - A1, ord=np.inf) / np.linalg.norm(A1, ord=np.inf)
    i += 1

  return A1

#=================================================================
#Генерация случайного вектора из 3-х элементов в диапазоне от -3 до 3
def generationRandomVector(elem = 3, start = -3, end = 3):
  vector = []
  for i in range(elem):
    vector.append(random.uniform(start, end))
  return vector

#=================================================================
#создание столбца таблицы
def createVariants(function, x, v, typeFunc = 1, elem = 100):
  vector = []

  if(typeFunc == 0):
    for i in range(elem):
      vector.append(function(generationRandomVector(), generationRandomVector()))
  else:
    for i in range(elem):
      vector.append(function(x[i], v[i]))

  return vector

#=================================================================
#count(x, v, y)
def createTableDOM(functions, count, step, oldTable = []):
  table = []
  vector = []
  columns = createColumns(step, count)

  if(step == 0):
    for i in range(sum(count[0:2])):
      table.append(createVariants(functions[i], [], [], 0)) #xi, vi

  else:
    for i in range(count[0]): #xi
      table.append(createVariants(functions[i], (np.array(oldTable))[:, 0:count[0]], (np.array(oldTable))[:, count[0]:sum(count[0:2])]))
    for i in range(count[1]): #vi
      table.append(createVariants(functions[count[0] + i], [], [], 0))

  for i in range(count[2]): #yi
    table.append(createVariants(functions[sum(count[0:2]) + i], (np.array(table).T)[:, 0:count[0]], (np.array(table).T)[:, count[0]:sum(count[0:2])]))

  table = pd.DataFrame(np.array(table).T, columns = columns)
  return table

def createColumns(step, count):
  columns = []
  for i in range(count[0]):
    columns.append("x" + str(i + 1) + "(" + str(step) + ")")
  for i in range(count[1]):
    columns.append("v" + str(i + 1) + "(" + str(step) + ")")
  for i in range(count[2]):
    columns.append("y" + str(i + 1) + "(" + str(step) + ")")
  return columns

In [107]:
#functions = [x1, x2, x3, v1, v2, v3, y1, y2, y3]
model_0 = createTableDOM(functions, count, 0)
model_0

x1(0)     x2(0)     x3(0)     v1(0)      v2(0)      v3(0)     y1(0)  \
0   0.240224 -0.067553 -0.988833  7.443165 -14.508844  -0.045140  3.371800   
1   0.898088  0.993477  0.415187 -1.333711  83.995092   4.588699 -1.138835   
2   0.329065  0.356446 -0.939772 -8.827632  55.241211   0.602039 -2.791064   
3  -0.997272  0.942287  0.924599  6.911193  -6.657300  17.829991 -7.090578   
4  -0.196063  0.599528 -0.982053  0.247097  91.703623  -0.382091 -0.027705   
..       ...       ...       ...       ...        ...        ...       ...   
95  0.442913  0.825467  0.997613 -0.965136 -71.501849   2.549445 -0.313124   
96  0.822288  0.765067 -0.287079 -0.021502  -5.538685   1.460788 -0.018330   
97 -0.689807 -0.156735  0.919863  4.756689  51.900766   2.247994 -6.883565   
98 -0.999794  0.929996 -0.912119  1.720164  98.368579   2.766874 -1.783181   
99 -0.568440 -0.985742 -0.196270  3.067452  46.277287   3.945875 -1.324108   

       y2(0)      y3(0)  
0   0.212425  -0.045140  
1   0.996173   4.588699  
2   0.752545   0.602039  
3   0.922974  17.829991  
4   0.610624  -0.382091  
..       ...        ...  
95  0.747091   2.549445  
96  0.996973   1.460788  
97  0.882798   2.247994  
98  0.604988   2.766874  
99  0.848724   3.945875  

[100 rows x 9 columns]

In [108]:
model_1 = createTableDOM(functions, count, 1, np.array(model_0))
model_1

<ipython-input-102-2055c8b71a7d>:8: RuntimeWarning: overflow encountered in double_scalars
  return math.sin(math.tan(x[2] * v[2]) - 3**(v[0]))


ValueError: ignored